# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Urmove' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Urmove
  # Layouts
  pod 'SnapKit', '~> 4.0.0'
  #KEYBOARD
  pod 'IQKeyboardManagerSwift'
  #FACEBOOK
  pod 'FacebookLogin'
  # Networking
  pod 'Alamofire'
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Activity
  pod 'NVActivityIndicatorView'
  # Google
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  # SLIDER
  pod 'MSCircularSlider'
  # Segment
  pod 'SJFluidSegmentedControl', :git => 'https://github.com/adornoventura/SJFluidSegmentedControl.git'
  # ALERTS
  pod 'EZAlertController', '3.2'
  pod 'Alertift', '~> 3.0'
  # TEXT FIELDS
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'CBPinEntryView'
  target 'UrmoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UrmoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
